Mvc1VaccinDemo/ViewModels/PersonViewModel.cs
namespace Mvc1VaccinDemo.ViewModels
{
    public class PersonViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PersonalNumber { get; set; }
        public string EmailAddress { get; set; }
    }
}

Mvc1VaccinDemo/ViewModels/SelectPersonViewModel.cs
using System;

namespace Mvc1VaccinDemo.ViewModels
{
    public class SelectPersonViewModel
    {
        public string Name { get; set; }
        public string PersonalNumber { get; set; }
        public string NextVaccinDate { get; set; }
        public string VaccineringsFas { get; set; }
    }
}

Mvc1VaccinDemo/Controllers/PersonController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mvc1VaccinDemo.Data;
using Mvc1VaccinDemo.Services.Krisinformation;
using Mvc1VaccinDemo.ViewModels;

namespace Mvc1VaccinDemo.Controllers
{
    public class PersonController : BaseController
    {
        public PersonController(ApplicationDbContext dbContext, IKrisInfoService krisInfoService)
            : base(dbContext, krisInfoService)
        {
        }

        // GET
        [Authorize(Roles = "Admin, Nurse")]
        public IActionResult Index(string q)
        {
           var viewModel = new PersonIndexViewModel();

            viewModel.Personer = _dbContext.Personer
                .Where(r => q == null || r.Name.Contains(q) || r.PersonalNumber.Contains(q))
                .Select(person => new PersonViewModel
                {
                    Id = person.Id,
                    Name = person.Name,
                    EmailAddress = person.EmailAddress,
                    PersonalNumber = person.PersonalNumber
                }).ToList();

            return View(viewModel);
        }


        [Authorize(Roles = "Admin, Nurse")]
        public IActionResult _SelectPerson(int id)
        {
            var viewModel = new SelectPersonViewModel();
            var p = _dbContext.Personer.Include(p=>p.VaccineringsFas).First(r => r.Id == id);

            viewModel.Name = p.Name;
            viewModel.PersonalNumber = p.PersonalNumber;
            viewModel.NextVaccinDate = p.PreliminaryNextVaccinDate.HasValue
                ? p.PreliminaryNextVaccinDate.Value.ToString("yyyy-MM-dd")
                : "";
            viewModel.VaccineringsFas = p.VaccineringsFas.Name;
            return View(viewModel);
        }



        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int Id)
        {
            var viewModel = new PersonEditViewModel();

            var dbPerson = _dbContext.Personer.Include(r=>r.VaccineringsFas).First(r => r.Id == Id);

            viewModel.Id = dbPerson.Id;
            viewModel.Name = dbPerson.Name;
            viewModel.EmailAddress = dbPerson.EmailAddress;
            viewModel.PersonalNumber = dbPerson.PersonalNumber;
            viewModel.City = dbPerson.City;
            viewModel.PostalCode = dbPerson.PostalCode;
            viewModel.PreliminaryNextVaccinDate = dbPerson.PreliminaryNextVaccinDate;
            viewModel.StreetAddress = dbPerson.StreetAddress;
            
            viewModel.SelectedVaccineringsFasId = dbPerson.VaccineringsFas.Id;
            viewModel.AllaVaccineringsFaser = GetAllVaccineringsFaserAsListItems(); 

            return View(viewModel);
        }

        private List<SelectListItem> GetAllVaccineringsFaserAsListItems()
        {
            var list = new List<SelectListItem>();
            list.AddRange(_dbContext.VaccineringsFaser.Select(r=>new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Name
            }));
            return list;

        }
    }
}

Mvc1VaccinDemo/Controllers/VaccinController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Connections.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mvc1VaccinDemo.Data;
using Mvc1VaccinDemo.Services;
using Mvc1VaccinDemo.Services.Krisinformation;
using Mvc1VaccinDemo.ViewModels;

namespace Mvc1VaccinDemo.Controllers
{
    public class VaccinController : BaseController
    {
        private readonly IOrderedVaccinService _orderedVaccinService;

        public VaccinController(ApplicationDbContext dbContext, IOrderedVaccinService orderedVaccinService, IKrisInfoService krisInfoService)
            : base(dbContext, krisInfoService)
        {
            _orderedVaccinService = orderedVaccinService;
        }


        public IActionResult SearchResult(string q)
        {
            var viewModel = new VaccinSearchResultViewModel();

            viewModel.Vacciner = _dbContext.Vacciner.Include(r => r.Supplier)
                .Where(r => q == null || r.Namn.Contains(q) || r.Supplier.Name.Contains(q))
                .Select(dbVacc => new VaccinViewModel
                {
                    Id = dbVacc.Id,
                    Supplier = dbVacc.Supplier.Name,
                    Name = dbVacc.Namn
                }).ToList();


            return View(viewModel);

        }


        // Kunna nås av "Admin"
        // men INTE av "Nurse" 
        //
        //[Authorize(Roles="Admin")]
        //   /Vaccin?q=qwer
        public IActionResult Index(string q)
        {
            var viewModel = new VaccinIndexViewModel();

            viewModel.Vacciner = _dbContext.Vacciner.Include(r=>r.Supplier)
                .Where(r=> q == null || r.Namn.Contains(q) || r.Supplier.Name.Contains(q) )
                .Select(dbVacc => new VaccinViewModel
            {
                Id = dbVacc.Id,
                Supplier = dbVacc.Supplier.Name,
                Name = dbVacc.Namn
            }).ToList();


            return View(viewModel);
        }

        public IActionResult _SelectVaccine(int SelectedId)
        {
            var viewModel = new SelectVaccineViewModel();
            var selectedVaccin = _dbContext.Vacciner.First(r => r.Id == SelectedId);
            viewModel.SelectedVaccinName = selectedVaccin.Namn;
            var result = _orderedVaccinService.GetTotal(selectedVaccin.Namn);
            viewModel.FirstDeliveryDate = result.FirstDeliveryDate;
            viewModel.NrInFirstDelivery = result.NrInFirstDelivery;
            viewModel.NrOrdered = result.NrOrdered;

            return View(viewModel);
        }

        //[Authorize(Roles = "Admin")]
        public IActionResult New()
        {
            var viewModel = new VaccinNewViewModel();
            viewModel.Types = GetTypeSelectListItems();
            viewModel.AllSuppliers = GetSuppliersListItems();

            return View(viewModel);
        }

        //[Authorize(Roles = "Admin")]
        [HttpPost]

        public IActionResult New(VaccinNewViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var dbVaccin = new Vaccin();
                _dbContext.Vacciner.Add(dbVaccin);
                dbVaccin.Supplier = _dbContext.Suppliers.First(r => r.Id == viewModel.SelectedSupplierId);
                dbVaccin.Type = (Vaccin.VaccinType)viewModel.Type;
                dbVaccin.Namn = viewModel.Namn;
                dbVaccin.AntalDoser = viewModel.AntalDoser;
                dbVaccin.EuOkStatus = viewModel.EuOkStatus;
                dbVaccin.Comment = viewModel.Comment;
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            viewModel.AllSuppliers = GetSuppliersListItems();
            viewModel.Types = GetTypeSelectListItems();
            return View(viewModel);
        }

        //[Authorize(Roles = "Admin")]
        public IActionResult Edit(int Id)
        {
            var viewModel = new VaccinEditViewModel();

            var dbVaccin = _dbContext.Vacciner.Include(p=>p.Supplier).First(r => r.Id == Id);

            viewModel.Id = dbVaccin.Id;
            viewModel.SelectedSupplierId = dbVaccin.Supplier.Id;
            viewModel.AllSuppliers = GetSuppliersListItems();
            viewModel.EuOkStatus = dbVaccin.EuOkStatus;
            viewModel.Namn = dbVaccin.Namn;
            viewModel.AntalDoser = dbVaccin.AntalDoser;
            viewModel.Comment = dbVaccin.Comment; 

            viewModel.Type = (int)dbVaccin.Type;
            viewModel.Types = GetTypeSelectListItems();

            viewModel.IsActive = true;

            return View(viewModel);
        }

        private List<SelectListItem> GetSuppliersListItems()
        {
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem {  Value="0", Text = "..please select..."  });

            list.AddRange(_dbContext.Suppliers.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id.ToString()
            }));
            return list;
        }


        //[Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(int Id, VaccinEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var dbVaccin = _dbContext.Vacciner.Include(p => p.Supplier).First(r => r.Id == Id);
                dbVaccin.Supplier = _dbContext.Suppliers.First(r => r.Id == viewModel.SelectedSupplierId);
                dbVaccin.Type = (Vaccin.VaccinType)viewModel.Type;
                dbVaccin.Namn = viewModel.Namn;
                dbVaccin.AntalDoser = viewModel.AntalDoser;
                dbVaccin.EuOkStatus = viewModel.EuOkStatus;
                dbVaccin.Comment = viewModel.Comment;
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            viewModel.AllSuppliers = GetSuppliersListItems();
            viewModel.Types = GetTypeSelectListItems();
            return View(viewModel);
        }
        /*
            if (ModelState.IsValid)
            {
                //ALLT ÄR OK!!!
                //Spara i databas...
                //kanske redirect to index
            }
            return View(viewModel);

         *
         */

            ////namn=varde&namn2=varde&namn3=varde
            //[HttpPost]
            //public IActionResult Edit(int Id, VaccinEditViewModel viewModel)
            //{
            //    if (ModelState.IsValid)
            //    {
            //        var dbVaccin = _dbContext.Vacciner.Include(p => p.Supplier)
            //            .First(r => r.Id == Id);
            //        dbVaccin.Namn = viewModel.Namn;
            //        dbVaccin.Type = (Vaccin.VaccinType) viewModel.Type;
            //        _dbContext.SaveChanges();
            //        return RedirectToAction("Index");
            //    }
            //    return View(viewModel);
            //}



            List<SelectListItem> GetTypeSelectListItems()
        {
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem("Okänd", "0"));
            list.Add(new SelectListItem("mRNA", "1"));
            list.Add(new SelectListItem("Vector", "2"));
            return list;
        }



    }
}

Mvc1VaccinDemo/Views/Person/Edit.cshtml
@model Mvc1VaccinDemo.ViewModels.PersonEditViewModel  


@{
    ViewData["Title"] = "Edit person";
}

<section class="py-5">
    <div class="row">
        <div class="col-lg-12 mb-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="h6 text-uppercase mb-0">Edit Person</h3>
                </div>
                
                <div class="card-body">
                    <form method="post" asp-controller="Person" asp-action="Edit">


                        <div class="form-group">
                            <label asp-for="Name">Namn</label>
                            <input class="form-control" asp-for="Name">
                            <span asp-validation-for="Name" class="field-validation-error"></span>
                        </div>


                        <div class="form-group">
                            <label asp-for="PersonalNumber">Personnummer</label>
                            <input class="form-control" asp-for="PersonalNumber">
                            <span asp-validation-for="PersonalNumber" class="field-validation-error"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="EmailAddress">Email</label>
                            <input class="form-control" asp-for="EmailAddress">
                            <span asp-validation-for="EmailAddress" class="field-validation-error"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="StreetAddress">Gatuadress</label>
                            <input class="form-control" asp-for="StreetAddress">
                            <span asp-validation-for="StreetAddress" class="field-validation-error"></span>
                        </div>


                        <div class="form-group">
                            <label asp-for="PostalCode">Postnummer</label>
                            <input class="form-control" asp-for="PostalCode">
                            <span asp-validation-for="PostalCode" class="field-validation-error"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="City">Stad</label>
                            <input class="form-control" asp-for="City">
                            <span asp-validation-for="City" class="field-validation-error"></span>
                        </div>



                        <div class="form-group">
                            <label asp-for="PreliminaryNextVaccinDate">Nästa vaccinering (prel)</label>
                            <input class="form-control" asp-for="PreliminaryNextVaccinDate">
                            <span asp-validation-for="PreliminaryNextVaccinDate" class="field-validation-error"></span>
                        </div>




                        <div class="form-group">
                            <label asp-for="SelectedVaccineringsFasId">Vaccineringsfas</label>
                            <select class="form-control"
                                    asp-for="SelectedVaccineringsFasId"
                                    asp-items="Model.AllaVaccineringsFaser"></select>
                        </div>








                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

            </div>

        </div>
    </div>
</section>

Mvc1VaccinDemo/Views/Person/Index.cshtml
@using System.Collections.Specialized
@model Mvc1VaccinDemo.ViewModels.PersonIndexViewModel

@{
    ViewData["Title"] = "Personer";
}
<section class="py-5">

    <div class="row">
        <div class="col-lg-12 mb-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="h6 text-uppercase mb-0">Sök</h3>
                </div>
                <div class="card-body">


                    <form method="get" asp-controller="Person" asp-action="Index">

                        <div class="form-row align-items-center">
                            <div class="col-auto">
                                <input type="text" class="form-control" asp-for="q">
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-primary">Sök</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>


    <div id="selectPersonPlaceHolder">

    </div>


    <div class="row">

        @*<form >

                <div class="form-row align-items-center">
                    <div class="col-auto">
                        <label for="SearchWord">Sök:</label>
                    </div>
                    <div class="col-auto">
                        <input type="text" class="form-control" asp-for="SearchWord">
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary">Sök</button>
                    </div>
                </div>

            </form>*@


        <div class="col-lg-12 mb-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="h6 text-uppercase mb-0">Person</h3>
                </div>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Personnummer</th>
                                <th scope="col">Namn</th>
                                <th scope="col">Email</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var personViewModel in Model.Personer)
                            {
                                <tr>
                                    <td>@personViewModel.PersonalNumber</td>
                                    <td>@personViewModel.Name</td>
                                    <td>@personViewModel.EmailAddress</td>
                                    <td><a href="#" onclick="FetchPerson(@personViewModel.Id); return false;" class="btn btn-secondary active" role="button" aria-pressed="true">Show details</a></td>
                                    <td><a asp-controller="Person" asp-action="Edit" asp-route-Id="@personViewModel.Id" class="btn btn-secondary active" role="button" aria-pressed="true">Edit</a></td>
                                </tr>
                            }

                        </tbody>
                    </table>


                </div>
            </div>
        </div>

        <a asp-controller="Person" asp-action="New" class="btn btn-secondary" role="button" aria-pressed="true">
            Create new
        </a>


    </div>
</section>

@section Scripts
{
    <script>
        function FetchPerson(id) {
            $.ajax({
                url: "/Person/_SelectPerson/" + id,
                success: function (result) {
                    $('#selectPersonPlaceHolder').html(result);
                }
            });
        }
    </script>    
}

Mvc1VaccinDemo/Views/Person/New.cshtml
@model Mvc1VaccinDemo.ViewModels.VaccinNewViewModel


@{
    ViewData["Title"] = "Nytt vaccin";
}



<section class="py-5">
    <div class="row">
        <div class="col-lg-12 mb-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="h6 text-uppercase mb-0">New Vaccin</h3>
                </div>

                <div class="card-body">
                    <form asp-controller="Vaccin" asp-action="New" method="post">
                        <div class="form-group">
                            <label asp-for="Namn">Namn</label>
                            <input class="form-control" asp-for="Namn">
                        </div>
                        <div class="form-group">
                            <label asp-for="SelectedSupplierId">Supplier</label>
                            <select class="form-control"
                                    asp-for="SelectedSupplierId"
                                    asp-items="Model.AllSuppliers"></select>
                            <span asp-validation-for="SelectedSupplierId" class="field-validation-error"></span>
                        </div>


                        <div class="form-group">
                            <label asp-for="EuOkStatus">Okstatus</label>
                            <input class="form-control" asp-for="EuOkStatus">
                        </div>
                        <div class="form-group">
                            <label asp-for="Type">Type</label>
                            <select class="form-control" asp-for="Type" asp-items="Model.Types"></select>
                        </div>


                        <div class="form-group">
                            <label asp-for="AntalDoser">Antal doser</label>
                            <input class="form-control" asp-for="AntalDoser">
                            <span asp-validation-for="AntalDoser" class="input-validation-error"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Comment">Comment</label>
                            <textarea rows="5" cols="30"
                                      class="form-control" asp-for="Comment"></textarea>
                            <span asp-validation-for="Comment" class="field-validation-error"></span>
                        </div>


                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

            </div>

        </div>
    </div>
</section>

Mvc1VaccinDemo/Views/Person/_SelectPerson.cshtml
@model Mvc1VaccinDemo.ViewModels.SelectPersonViewModel


@{
    Layout = null;    
}


<div class="row">
    <div class="col-lg-12">
        <div class="card mb-5 mb-lg-0">
            <div class="card-header">
                <h2 class="h6 mb-0 text-uppercase">VALD PERSON: @Model.Name, @Model.PersonalNumber</h2>
            </div>
            <div class="card-body">
                <p class="text-gray mb-5">Uppgifter är preliminära</p>
                <div class="d-flex justify-content-between align-items-start align-items-sm-center mb-4 flex-column flex-sm-row">
                    <div class="left d-flex align-items-center">
                        <div class="icon icon-lg shadow mr-3 text-gray"><i class="fab fa-dropbox"></i></div>
                        <div class="text">
                            <h6 class="mb-0 d-flex align-items-center"> <span>Nästa planerade vaccinationstillfälle</span><span class="dot dot-sm ml-2 bg-violet"></span></h6><small class="text-gray">beroende på leveranser</small>
                        </div>
                    </div>
                    <div class="right ml-5 ml-sm-0 pl-3 pl-sm-0 text-violet">
                        <h5>@Model.NextVaccinDate</h5>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-start align-items-sm-center mb-4 flex-column flex-sm-row">
                    <div class="left d-flex align-items-center">
                        <div class="icon icon-lg shadow mr-3 text-gray"><i class="fab fa-apple"></i></div>
                        <div class="text">
                            <h6 class="mb-0 d-flex align-items-center"> <span>Vaccineringsfas</span><span class="dot dot-sm ml-2 bg-green"></span></h6><small class="text-gray">Aktuell uppgift</small>
                        </div>
                    </div>
                    <div class="right ml-5 ml-sm-0 pl-3 pl-sm-0 text-green">
                        <h5>@Model.VaccineringsFas</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br />